// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bibliography.proto

package org.example.proto;

public interface BibliographyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Bibliography)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string author = 1;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>string author = 1;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 1;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string genre = 2;</code>
   * @return Whether the genre field is set.
   */
  boolean hasGenre();
  /**
   * <code>string genre = 2;</code>
   * @return The genre.
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 2;</code>
   * @return The bytes for genre.
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>repeated string books = 4;</code>
   * @return A list containing the books.
   */
  java.util.List<java.lang.String>
      getBooksList();
  /**
   * <code>repeated string books = 4;</code>
   * @return The count of books.
   */
  int getBooksCount();
  /**
   * <code>repeated string books = 4;</code>
   * @param index The index of the element to return.
   * @return The books at the given index.
   */
  java.lang.String getBooks(int index);
  /**
   * <code>repeated string books = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the books at the given index.
   */
  com.google.protobuf.ByteString
      getBooksBytes(int index);
}
