// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bibliography.proto

package org.example.proto;

/**
 * Protobuf type {@code Bibliography}
 */
public final class Bibliography extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Bibliography)
    BibliographyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Bibliography.newBuilder() to construct.
  private Bibliography(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Bibliography() {
    author_ = "";
    genre_ = "";
    books_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Bibliography();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Bibliography(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            author_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            genre_ = s;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            quantity_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              books_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            books_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        books_ = books_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.BibliographyProtos.internal_static_Bibliography_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.BibliographyProtos.internal_static_Bibliography_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.Bibliography.class, org.example.proto.Bibliography.Builder.class);
  }

  private int bitField0_;
  public static final int AUTHOR_FIELD_NUMBER = 1;
  private volatile java.lang.Object author_;
  /**
   * <code>string author = 1;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string author = 1;</code>
   * @return The author.
   */
  @java.lang.Override
  public java.lang.String getAuthor() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      author_ = s;
      return s;
    }
  }
  /**
   * <code>string author = 1;</code>
   * @return The bytes for author.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      author_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENRE_FIELD_NUMBER = 2;
  private volatile java.lang.Object genre_;
  /**
   * <code>string genre = 2;</code>
   * @return Whether the genre field is set.
   */
  @java.lang.Override
  public boolean hasGenre() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string genre = 2;</code>
   * @return The genre.
   */
  @java.lang.Override
  public java.lang.String getGenre() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genre_ = s;
      return s;
    }
  }
  /**
   * <code>string genre = 2;</code>
   * @return The bytes for genre.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenreBytes() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 3;
  private int quantity_;
  /**
   * <code>int32 quantity = 3;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int BOOKS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList books_;
  /**
   * <code>repeated string books = 4;</code>
   * @return A list containing the books.
   */
  public com.google.protobuf.ProtocolStringList
      getBooksList() {
    return books_;
  }
  /**
   * <code>repeated string books = 4;</code>
   * @return The count of books.
   */
  public int getBooksCount() {
    return books_.size();
  }
  /**
   * <code>repeated string books = 4;</code>
   * @param index The index of the element to return.
   * @return The books at the given index.
   */
  public java.lang.String getBooks(int index) {
    return books_.get(index);
  }
  /**
   * <code>repeated string books = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the books at the given index.
   */
  public com.google.protobuf.ByteString
      getBooksBytes(int index) {
    return books_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, author_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, genre_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, quantity_);
    }
    for (int i = 0; i < books_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, books_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, author_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, genre_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, quantity_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < books_.size(); i++) {
        dataSize += computeStringSizeNoTag(books_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getBooksList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.Bibliography)) {
      return super.equals(obj);
    }
    org.example.proto.Bibliography other = (org.example.proto.Bibliography) obj;

    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (hasGenre() != other.hasGenre()) return false;
    if (hasGenre()) {
      if (!getGenre()
          .equals(other.getGenre())) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (getQuantity()
          != other.getQuantity()) return false;
    }
    if (!getBooksList()
        .equals(other.getBooksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    if (hasGenre()) {
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + getGenre().hashCode();
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
    }
    if (getBooksCount() > 0) {
      hash = (37 * hash) + BOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getBooksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.Bibliography parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Bibliography parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Bibliography parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Bibliography parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Bibliography parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Bibliography parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Bibliography parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Bibliography parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Bibliography parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.proto.Bibliography parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Bibliography parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Bibliography parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.Bibliography prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Bibliography}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Bibliography)
      org.example.proto.BibliographyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.BibliographyProtos.internal_static_Bibliography_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.BibliographyProtos.internal_static_Bibliography_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.Bibliography.class, org.example.proto.Bibliography.Builder.class);
    }

    // Construct using org.example.proto.Bibliography.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      author_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      genre_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      books_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.BibliographyProtos.internal_static_Bibliography_descriptor;
    }

    @java.lang.Override
    public org.example.proto.Bibliography getDefaultInstanceForType() {
      return org.example.proto.Bibliography.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.Bibliography build() {
      org.example.proto.Bibliography result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.Bibliography buildPartial() {
      org.example.proto.Bibliography result = new org.example.proto.Bibliography(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.author_ = author_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.genre_ = genre_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000004;
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        books_ = books_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.books_ = books_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.Bibliography) {
        return mergeFrom((org.example.proto.Bibliography)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.Bibliography other) {
      if (other == org.example.proto.Bibliography.getDefaultInstance()) return this;
      if (other.hasAuthor()) {
        bitField0_ |= 0x00000001;
        author_ = other.author_;
        onChanged();
      }
      if (other.hasGenre()) {
        bitField0_ |= 0x00000002;
        genre_ = other.genre_;
        onChanged();
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      if (!other.books_.isEmpty()) {
        if (books_.isEmpty()) {
          books_ = other.books_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureBooksIsMutable();
          books_.addAll(other.books_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.proto.Bibliography parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.proto.Bibliography) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object author_ = "";
    /**
     * <code>string author = 1;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string author = 1;</code>
     * @return The author.
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string author = 1;</code>
     * @return The bytes for author.
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string author = 1;</code>
     * @param value The author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      author_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string author = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      author_ = getDefaultInstance().getAuthor();
      onChanged();
      return this;
    }
    /**
     * <code>string author = 1;</code>
     * @param value The bytes for author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      author_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genre_ = "";
    /**
     * <code>string genre = 2;</code>
     * @return Whether the genre field is set.
     */
    public boolean hasGenre() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string genre = 2;</code>
     * @return The genre.
     */
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genre = 2;</code>
     * @return The bytes for genre.
     */
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genre = 2;</code>
     * @param value The genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenre(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      genre_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenre() {
      bitField0_ = (bitField0_ & ~0x00000002);
      genre_ = getDefaultInstance().getGenre();
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 2;</code>
     * @param value The bytes for genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      genre_ = value;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 3;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000004;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList books_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureBooksIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        books_ = new com.google.protobuf.LazyStringArrayList(books_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string books = 4;</code>
     * @return A list containing the books.
     */
    public com.google.protobuf.ProtocolStringList
        getBooksList() {
      return books_.getUnmodifiableView();
    }
    /**
     * <code>repeated string books = 4;</code>
     * @return The count of books.
     */
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param index The index of the element to return.
     * @return The books at the given index.
     */
    public java.lang.String getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the books at the given index.
     */
    public com.google.protobuf.ByteString
        getBooksBytes(int index) {
      return books_.getByteString(index);
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param index The index to set the value at.
     * @param value The books to set.
     * @return This builder for chaining.
     */
    public Builder setBooks(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureBooksIsMutable();
      books_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param value The books to add.
     * @return This builder for chaining.
     */
    public Builder addBooks(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureBooksIsMutable();
      books_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param values The books to add.
     * @return This builder for chaining.
     */
    public Builder addAllBooks(
        java.lang.Iterable<java.lang.String> values) {
      ensureBooksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, books_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string books = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBooks() {
      books_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string books = 4;</code>
     * @param value The bytes of the books to add.
     * @return This builder for chaining.
     */
    public Builder addBooksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureBooksIsMutable();
      books_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Bibliography)
  }

  // @@protoc_insertion_point(class_scope:Bibliography)
  private static final org.example.proto.Bibliography DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.Bibliography();
  }

  public static org.example.proto.Bibliography getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bibliography>
      PARSER = new com.google.protobuf.AbstractParser<Bibliography>() {
    @java.lang.Override
    public Bibliography parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Bibliography(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Bibliography> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bibliography> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.Bibliography getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

